name: r2s_lean

on:
  repository_dispatch:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/r2s_lean_passwall_clash.yml'
      - '*.sh'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.sec_token }}
      sec_token: ${{ secrets.sec_token }}

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 0
          token: ${{ env.sec_token }}

      - name: Init Env
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          . init_env.sh
      
      - name: Repo Hash
        run: |
          ./set_repo_hash.sh Builder
      
      - name: Friendlywrt Source
        run: |
          . friendlywrt_source.sh

      - name: Patch Kernel
        run: |
          . patch_kernel_5.4.sh

      - name: Rebase on Lean
        run: |
          . rebase_on_lean.sh
      
      - name: Add Packages to Lean
        run: |
          . add_packages_to_lean.sh

      - name: Patches for Lean
        run: |
          . lean_patches.sh

      - name: Change Log
        id: changelog
        run: |
          ./changelog.sh

      - name: Download Clash Binary
        if: steps.changelog.outputs.changelog != ''
        run: |
          CLASH_VERSION=v0.19.0
          mkdir -p friendlywrt-rk3328/friendlywrt/package/base-files/files/usr/bin
          cd friendlywrt-rk3328/friendlywrt/package/base-files/files/usr/bin
          wget -O clash.gz https://github.com/Dreamacro/clash/releases/download/$CLASH_VERSION/clash-linux-armv8-$CLASH_VERSION.gz
          gunzip clash.gz
          chmod +x clash

      - name: Build Config
        if: steps.changelog.outputs.changelog != ''
        run: |
          cd friendlywrt-rk3328
          cat configs/config_rk3328 | grep "TARGET" > ../rk3328.config
          cat ../minimal_config.seed >> ../rk3328.config
          cat ../rk3328.config > configs/config_rk3328
          cat configs/config_rk3328
      
      - name: Build Friendlywrt
        if: steps.changelog.outputs.changelog != ''
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk
      
      - name: Zip Files
        if: steps.changelog.outputs.changelog != ''
        run: |
          gzip friendlywrt-rk3328/out/*.img

      - name: Assemble Artifact
        if: steps.changelog.outputs.changelog != ''
        id: assemble_artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          cd friendlywrt-rk3328/friendlywrt;./scripts/diffconfig.sh > ../../artifact/config.seed;cd ../../
          mv friendlywrt-rk3328/out/*img* ./artifact/
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/full.config
          zip -r artifact.zip -j artifact artifact/*
          release_tag=${{ steps.changelog.outputs.buildtag }}
          echo "##[set-output name=release_tag;]$release_tag"

      - name: Create Release
        if: steps.changelog.outputs.changelog != ''
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: steps.changelog.outputs.changelog != ''
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./artifact.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM.zip
          asset_content_type: application/zip
    
      - name: Push Change Log
        if: steps.changelog.outputs.changelog != ''
        run: |
          git pull --rebase --autostash
          git push
